### ISSUE TITLE
Roadmap update

### ISSUE THREAD

**Issue by phyzzle** [Zilliqa/docs#4]
Why is your roadmap not updated?.....
Last update was October 2017......
Any particular reason???

**Comment by bb111189** [comment]
It will need an update soon. We are aware of it. 

To give more clarity on the roadmap, we had hit a few milestone since Oct. For instance we release smart contract paper and open sourcing of code. However, we are slightly behind on testnet.

**Comment by bb111189** [comment]
Updated some time back. Issued closed.
